import {
    CtxMenu,
    Collection,
    View
} from "symposium";
import {
    EV_PANEL_ITEM_DBLCLICK,
    EV_PANEL_ITEM_CLICK,
    EV_CTX_MENU_ITEM_CLICK
} from "symposium";

import { Thumbnail } from "../models/thumbnail";
import { ThumbnailsPanelView, PagesPanelView } from "./panel/index";
import { CtxMenuView } from "./ctx_menu";

import {
    fetch_document,
    fetch_page_svg
} from "../requests";
import { ctx_menu_items } from "../ctx_menu_items";


class DocumentPanelView extends View {

    constructor(options={}) {

        super();

        let that = this;

        this.thumbnails_col = new Collection();
        this.thumbnails_view = new ThumbnailsPanelView({
            collection: this.thumbnails_col,
            options: options['thumbnails']
        });

        this.pages_col = new Collection();
        this.pages_view = new PagesPanelView({
            collection: this.pages_col,
            options: options['pages']
        });

        this.ctx_menu_col = new CtxMenu();
        this.ctx_menu_view = new CtxMenuView({
            collection: this.ctx_menu_col,
            options: options['ctx_menu']
        });
        this.options = options;

        this.pages_col.on("change", this.on_svg_load, this);
        this.pages_col.on("reset", this.on_pages_reset, this);

        this.thumbnails_col.on("reset", this.on_thumbnails_reset, this);
        this.ctx_menu_col.on("reset", this.render_ctx_menu, this);
        // events generated by user
        this.thumbnails_view.on(EV_PANEL_ITEM_CLICK, this.on_thumbnail_clicked, this);
        this.thumbnails_view.on(EV_PANEL_ITEM_DBLCLICK, this.on_thumbnail_dblclicked, this);
        this.ctx_menu_view.on(
            EV_CTX_MENU_ITEM_CLICK,
            this.on_menu_item_click,
            this
        );

        // zoom event sent from outside (by zoom selector)
        this.on("zoom", (zoom_value) => {
            that.pages_view.trigger("zoom", zoom_value);
        });

        this.ctx_menu_col.reset(ctx_menu_items);
    }

    initial_fetch(doc) {
        let that = this;

        fetch_document(doc).then((pages) => {

            let new_thumb_col = new Collection();

            that.pages_col.reset(pages);
            new_thumb_col = pages.map((page) => {
                return new Thumbnail({
                    id: page.id,
                    page_num: page.page_num
                });
            });
            that.thumbnails_col.reset(new_thumb_col);
        }).catch((error) => {
            alert(`Error while fetching document '${doc}': ${error}`);
        });
    }

    on_svg_load(page) {
        this.pages_view.render(page);
        this.thumbnails_view.render(page);
    }

    get_selection() {
        return this.thumbnails_col.filter(
            (page) => { return page.is_selected; }
        );
    }

    node_selected({node, selection}) {
        this.trigger(
            EV_PANEL_ITEM_SELECTED,
            {node, selection}
        );
        this.ctx_menu_model.trigger(
            EV_PANEL_ITEM_SELECTED,
            {node, selection}
        );
    }

    on_menu_item_click(action) {
        action.run({
            selection: this.get_selection(),
        });
    }

    on_thumbnail_clicked(thumbnail) {
        //console.log(`on_thumbnail_clicked ${thumbnail}`);
    }

    on_thumbnail_dblclicked(thumbnail) {
        //console.log("on_thumbnail_dblclicked");
        this.pages_view.scroll_to(thumbnail.id);
    }

    on_pages_reset() {

        this.pages_view.render();
        this.pages_col.forEach((page) => {
            fetch_page_svg(page);
        });
    }

    on_thumbnails_reset() {
        this.thumbnails_view.render();
    }

    render_ctx_menu() {
        this.ctx_menu_view.render();
    }

    reset(item_or_items) {
        this.panel_model.reset(item_or_items);
    }

}

export { DocumentPanelView };